### PR TITLE
Add RevenueRecognitionRuleName to the list of excluded fields from query()

### PR DESCRIPTION
**Pull request by anfleene**

### CODE REVIEW

**Comment by pete2786** [comment]
If we are excluding this one, we should also exclude `:deferred_revenue_account` and `:recognized_revenue_account` to the excluded list. Per the zuora documentation all of those fields only come with Z-Finance.

**Comment by pete2786** [comment]
https://knowledgecenter.zuora.com/BC_Developers/SOAP_API/E1_SOAP_API_Object_Reference/ProductRatePlanCharge

**Comment by pete2786** [comment]
Otherwise :+1:

**Comment by anfleene** [comment]
@pete2786 updated.

**Comment by pete2786** [comment]
:+1:

**Pull request merged**
