### PR TITLE
Exclude RevenueRecogntionRuleName from queries on RatePlanCharge

### PR DESCRIPTION
**Pull request by scottpayne**
Fix for issue #48

### CODE REVIEW

**Comment by scottpayne** [comment]
I've had a look at the change for issue #48 and it doesn't quite solve our problem. That fix excludes the field from `ProductRatePlanCharge`, whereas the issue is having the field on `RatePlanCharge`.

I have a question too. I saw @pete2786's comment about excluding other Z-Finance fields in #49 and wonder if it's necessary to exclude fields in case Z-Finance is turned off? AFAIK the downloaded WSDL won't have any Z-Finance fields if you don't have Z-Finance enabled (I might be wrong though).

**Comment by rdavila** [comment]
👍 I'm doing this by Reopening the Class from a Rails initializer right now.

**Comment by chadxz** [comment]
Is there anything blocking this fix from being merged? Any way we could help?

**Comment by anfleene** [comment]
Nope, sorry.

**Comment by anfleene** [comment]
Fixed in [2.5.2](https://rubygems.org/gems/active_zuora/versions/2.5.2)

**Comment by chadxz** [comment]
Thank you :)

**Pull request merged**
