### PR TITLE
support for batch subscribe requests

### PR DESCRIPTION
**Pull request by jonnymacs**
Per the Zuora docs https://knowledgecenter.zuora.com/D_SOAP_API/E_SOAP_API_Calls/subscribe_call

The subscribe() call bundles the information required to create one or more new subscriptions.

This pr aims to support creating multiple subscriptions at once.

The approach is to use a CollectionProxy - analogous to an ActiveRecord::Associations::CollectionProxy that includes a BatchSubscribe module.  The BatchSubscribe module has a batch_subscribe method that builds a subscribe xml from a collection.

### CODE REVIEW

**Comment by anfleene** [comment]
We ran into something similar recently try
`ActiveZuora::Base.connection.custom_header = {'CallOptions' => {'useSingleTransaction' => true}}`
That will force zuora to create all the objects in the same transaction.

**Comment by jonnymacs** [comment]
@anfleene thanks for the tip.  I tried it and I get the same result when issuing a batch subscribe and no account exists.

we're also having trouble with preview mode when the account does not exist - the preview invoice data is not returned.

I'm talking to a dev manager at Zuora and he's looking into it.  He thinks preview mode should work without an existing account, but he doesn't think they can support the batch subscribe without an existing account.

Seems the account must be created first before the batch subscribe, then you can set the account id in each of the the subscribe request account objects.  This actually fixes preview as well.  But it's not ideal...

I'll post any more info I get here.

**Comment by anfleene** [comment]
Ah ok. Seems like this code is still valid It will just have to be clear that you have to create the accounts first.

**Comment by jonnymacs** [comment]
follow up on the preview mode - contract dates are required for preview mode to work.

    :contract_effective_date
    :service_activation_date
    :contract_acceptance_date
  
still looking like real (non preview) is a no go w/o an account first though.  Not sure if the gem should be responsible to check for this though or not.  Seems like that belongs on the zuora docs.

**Comment by anfleene** [comment]
I think I agree that we shouldn't account for that in AZ. I'm sort of wondering how your test is passing though, unless I'm miss understanding the problem shouldn't the second subscription in your integration test fail?

**Comment by jonnymacs** [comment]
@anfleene - ah - ok.  I'm approaching zuora 3rd class archer status this week...

The issue with creating multiple subscriptions without an account actually only occurs when the payment method has already been setup (via hosted payment page or some other means), but not the account.  So the call has a payment method id, and an attempt to create an account with this payment method as the default payment method will cause problems.  For the first subscription the account is created and assigned the correct default payment method id but the subsequent subscriptions are not created with the error 

    INVALID_VALUE: This payment method has already been associated with a billing account. It cannot be used in a new subscription.

The reason the test passes is because the subscribe requests include a new payment method with payment data for each subscription.  So what is happening is zuora is creating 2 accounts and 2 payments methods, 2 subscriptions and 2 contacts...

the test then only deletes the first account.  So ur then left with a dirty integration env... you may want to go find and clean up any accounts that were created by running the test.  I've updated the PR to delete the 2nd account.

https://github.com/jonnymacs/active_zuora/commit/02d453eff0a65b51e6850fb5c5b641a4f499ed23

**Comment by anfleene** [comment]
Wow. Ok, thanks for fixing the test I totally missed that. Nice work sorting this out. I think we should roll with this if you are ready. I think this code is a good addition to support your use case. IIRC you can't share payment methods so that all seems legit.

If you're satisfied with this I'll merge it and get it released.

**Comment by jonnymacs** [comment]
@anfleene uw - and thank you for quickly calling out the mystery of why the test is passing.  It totally contradicted my first comment and I didn't even see it.

By all means, yes please merge and release.

And thanks for all ur help - great gem, _way_ better than the zuora sponsored client.

**Comment by anfleene** [comment]
v2.2.0 Is live on Rubygems.

**Pull request merged**
